module.exports = {

	DIGITAL_PRINT_MAX_AMOUNT: 250,

	DIGITAL_PRINT: "DIGITAL",

	OFFSET_PREPRINT_PAPER_AMOUNT: 250,

	OFFSET_PRINT: "OFFSET",

	CARTON_PRINT: "CARTON",

	POSTPROC_CREASING: "CREASING",

	POSTPROC_CREASING_V1_GSID: "ПЗРАБИБ1",

	POSTPROC_CREASING_V2_GSID: "ПЗРАБИБ2",

	POSTPROC_FOLDING: "FOLDING",

	POSTPROC_FOLDING_M_GSID: "ПЗРАФаФ1",

	POSTPROC_FOLDING_H_GSID: "ПЗРАФаФ2",

	POSTPROC_ROUNDING: "ROUNDING",

	POSTPROC_ROUNDING_H_GSID: "ПЗРАПоПР",

	RISOGRAPH_PRINT: "RISOGRAPH"

};

Object.freeze(module.exports);