module.exports = {

	DIGITAL_PRINT_MAX_AMOUNT: 250,

	DIGITAL_PRINT: "DIGITAL",

	OFFSET_PRINT: "OFFSET",

	CARTON_PRINT: "CARTON",

	POSTPROC_CREASING: "CREASING",

	POSTPROC_FOLDING: "FOLDING",

	POSTPROC_ROUNDING: "ROUNDING",

	RISOGRAPH_PRINT: "RISOGRAPH"

};

Object.freeze(module.exports);